# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gomokuai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Copy client build to server
        run: |
          mkdir -p server/public
          cp -r client/dist/* server/public/

      - name: Create deployment package
        run: |
          cd server
          # Remove dev dependencies and unnecessary files for production
          rm -rf node_modules
          npm ci --only=production
          
          # Remove unnecessary files for production deployment
          rm -f .env.example
          rm -f README.md
          rm -f server.log
          
          # Ensure public directory exists with built client
          if [ ! -d "public" ] || [ ! -f "public/index.html" ]; then
            echo "Error: Client build not found in public directory"
            exit 1
          fi

      - name: Verify deployment package
        run: |
          cd server
          echo "Contents of server directory:"
          ls -la
          echo "Contents of public directory:"
          ls -la public/ || echo "No public directory found"
          echo "Checking if server.js exists:"
          test -f server.js && echo "✅ server.js found" || echo "❌ server.js missing"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09FE046E7F1644D98588CEBD12422638 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E2A01D87834485EA047B6C9602B11CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69FCC417DD604CD0B30BB5E8F7F7FE07 }}
          allow-no-subscriptions: true

      - name: Set up application settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'gomokuai'
          app-settings-json: |
            [
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "GEMINI_API_KEY",
                "value": "${{ secrets.GEMINI_API_KEY }}"
              },
              {
                "name": "PORT",
                "value": "8080"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "20.x"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "1"
              },
              {
                "name": "WEBSITE_ENABLE_SYNC_UPDATE_SITE", 
                "value": "true"
              }
            ]

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gomokuai'
          package: .

      - name: Health Check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          
          # Get the actual deployment URL from Azure
          WEBAPP_URL="https://gomokuai-b7f4fxc7eagkb2gk.southeastasia-01.azurewebsites.net"
          echo "Testing deployment at: $WEBAPP_URL"
          
          # Try to access the health endpoint
          for i in {1..5}; do
            echo "Health check attempt $i of 5..."
            if curl -f -s "$WEBAPP_URL/api/health"; then
              echo "✅ Health check passed"
              break
            else
              echo "⏳ Health check attempt $i failed, retrying in 10 seconds..."
              sleep 10
            fi
          done
          
          # Check AI status endpoint
          echo "Checking AI services status..."
          curl -f -s "$WEBAPP_URL/api/ai/status" || echo "AI status check failed"
          
          # Try to access the main page
          echo "Checking main application..."
          curl -f -s "$WEBAPP_URL/" | head -5 || echo "Main page check failed"
          